### ISSUE TITLE
No module named 'controlnet_aux'

### ISSUE THREAD

**Issue by T3chRomanc3r** [kenneth2001/comfyui_controlnet_preprocessors#1]
```
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfyui_controlnet_preprocessors import preprocessor
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_preprocessors\__init__.py", line 1, in <module>
    from custom_nodes.comfyui_controlnet_preprocessors import preprocessor
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_preprocessors\preprocessor.py", line 3, in <module>
    from controlnet_aux import CannyDetector, MidasDetector, ZoeDetector, LeresDetector, NormalBaeDetector, OpenposeDetector, MLSDdetector, LineartDetector, LineartAnimeDetector, HEDdetector, PidiNetDetector, ContentShuffleDetector
ModuleNotFoundError: No module named 'controlnet_aux'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_preprocessors module for custom nodes: No module named 'controlnet_aux'
```

**Comment by T3chRomanc3r** [comment]
Issue has been resolved by running 
`pip install controlnet_aux`

**Comment by kenneth2001** [comment]
> Issue has been resolved by running 
> 
> `pip install controlnet_aux`

Thank you for trying.

**Comment by camoody1** [comment]
> Issue has been resolved by running `pip install controlnet_aux`

Where do I run this command? I'm using ComfyUI Portable on Windows and I'm not at all familiar with Python.

**Comment by kenneth2001** [comment]
> > Issue has been resolved by running `pip install controlnet_aux`
> 
> Where do I run this command? I'm using ComfyUI Portable on Windows and I'm not at all familiar with Python.

For your information, run `./python_embeded/python.exe -s -m pip install controlnet_aux`
